### PR TITLE
Update naming conventions

### PR DESCRIPTION
**Pull request by rgreinho**
Updates the naming conventions to match the latest outcome of the
discussion of the BNA Working Group.

Signed-off-by: Rémy Greinhofer <remy.greinhofer@gmail.com>

### CODE REVIEW

**Comment by robahtou** [comment]
@beckymasond @lalver1 @rgreinho 

I think this is really confusing have two types of versioning. From a user perspective, they have to remember which is which and for what asset. As time goes on, either viewing something like this on the web or in the code base or in the database, there is cognitive load to recall just to make sure you understand the versioning. Also, time relevant or not, I don't it warrants having to support two types of versioning, its just not that big of a deal. Just make it time relevant for all things. IMO.

I'd suggest go with one, make a reference to it in the docs, and a user can look at any asset and not think about it. I think the one that most users will clearly understand is `vYY.0M[.Minor]`. Then all assets will have the same version meaning:

```
city_ratings_v22.07.csv				(year + month)
template-scorecard-v22.04.svg  			(year + month)
chicago_illinois-scorecard-v24.05.pdf		(year + month + minor)
chicago_illinois-scorecard-v24.05.3.pdf	        (year + month + minor)
```

**Comment by rgreinho** [comment]
That makes sense @robahtou. 

Besides, since `vYY.0M[.Minor]` is the naming scheme of the BNA itself, it makes sense to keep only this one I think.

**Comment by lalver1** [comment]
After looking at this again, I agree @robahtou and @rgreinho , `vYY.0M[.Minor]` is sufficient to cover the names of assets and it aligns with the naming convention of BNA exports.

**Comment by beckymasond** [comment]
This alternative works for me.

Rebecca Davies

City Ratings <https://cityratings.peopleforbikes.org/> Program Director

(she/her)

PeopleForBikes

P.O. Box 2359 / Boulder, CO 80306

MOBILE: 503.577.9052

PeopleForBikes.org <https://www.PeopleForBikes.org>


<https://www.classy.org/give/117371/#!/donation/checkout>

**Comment by rgreinho** [comment]
Alright! Since everybody agreed, I updated the guidelines accordingly.

@lalver1 or @beckymasond can you review please?

**Review by lalver1 — APPROVED** [review]
Thanks @rgreinho , it looks great! 👍

**Comment by beckymasond** [comment]
Look great. Thanks for everyone's inputs and for updating this, @rgreinho!

**Pull request merged**
